CREATE TABLE `rutina_correctivo` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT,
    `titulo` varchar(150) DEFAULT NULL,
    `razon` varchar(100) DEFAULT NULL,
    `idcentro` bigint(20) DEFAULT NULL,
    `iddepartamento` bigint(20) DEFAULT NULL,
    `idestacione` bigint(20) DEFAULT NULL,
    `usr_resp` varchar(15) DEFAULT NULL,
    `fecha_eje` date DEFAULT NULL,
    `tipo_solucion` varchar(100) DEFAULT NULL,
    `fecha_corte` datetime DEFAULT NULL,
    `fecha_aviso` datetime DEFAULT NULL,
    `fecha_salida` datetime DEFAULT NULL,
    `fecha_llegada` datetime DEFAULT NULL,
    `fecha_superada` datetime DEFAULT NULL,
    `fecha_fin` datetime DEFAULT NULL,
    `usr_coord` varchar(15) DEFAULT NULL,
    `ticket_principal` varchar(150) DEFAULT NULL,
    `ticket_relacion` varchar(255) DEFAULT NULL,
    `atencion` varchar(100) DEFAULT NULL,
    `servicio_afecta` varchar(100) DEFAULT NULL,
    `estado_ticket` varchar(100) DEFAULT NULL,
    `en_plazo` varchar(10) DEFAULT NULL,
    `sistemafalla` varchar(150) DEFAULT NULL,
    `equipofalla` varchar(150) DEFAULT NULL,
    `tipofalla` varchar(150) DEFAULT NULL,
    `solucion` varchar(150) DEFAULT NULL,
    `descripcion_falla` varchar(255) DEFAULT NULL,
    `medidas_restituir` varchar(255) DEFAULT NULL,
    `estado_final` varchar(150) DEFAULT NULL,
    `causas` longtext,
    `partes_afectadas` longtext,
    `estaciones_afectadas` varchar(255) DEFAULT NULL,
    `desc_solucion` varchar(255) DEFAULT NULL,
    `descripcion_solucion` longtext,
    `aclarativos` longtext,
    `acciones_preventivas` longtext,
    `observaciones_fueraplazo` longtext,
    `observaciones` longtext,
    `pendiente_1` varchar(255) DEFAULT NULL,
    `pendiente_2` varchar(255) DEFAULT NULL,
    `pendiente_3` varchar(255) DEFAULT NULL,
    `pendiente_4` varchar(255) DEFAULT NULL,
    `pendiente_5` varchar(255) DEFAULT NULL,
    `usr_tec1` varchar(15) DEFAULT NULL,
    `usr_tec2` varchar(15) DEFAULT NULL,
    `notas` longtext,
    PRIMARY KEY (`id`)
);

alter table rutina_correctivo add foreign key (idcentro) references centro(idcentro);
alter table rutina_correctivo add foreign key (iddepartamento) references departamento(iddepartamento);
-- alter table rutina_correctivo add foreign key (idestacione) references estacionentel(idestacionentel); ERROR

alter table rutina_correctivo add column idgrupo bigint(20) after pendiente_5;
alter table rutina_correctivo add foreign key  (idgrupo) references grupo(idgrupo);