-- 29.07.2023
-- INSERTAR DATOS ENERGIA
-- insert into ticket_equipofalla (`idequipofalla`, `nombreequipofalla`, `idsistemafalla`, `activo`)
-- EQUIPOFALLA
insert into ticket_equipofalla values ('EE-020', 'SUMINISTRO DE ENERGIA COMERCIAL', 2, 1);
insert into ticket_equipofalla values ('EE-021', 'RED DE MEDIA TENSION', 2, 1);
insert into ticket_equipofalla values ('EE-022', 'RED DE BAJA TENSION', 2, 1);
insert into ticket_equipofalla values ('EE-023', 'TABLERO DE DISTRIBUCION PRINCIPAL (TDP) ENERGIA AC', 2, 1);
insert into ticket_equipofalla values ('EE-024', 'GRUPO GENERADOR', 2, 1);
insert into ticket_equipofalla values ('EE-025', 'TABLERO DE TRANSFERENCIA ATS', 2, 1);
insert into ticket_equipofalla values ('EE-026', 'SISTEMA FOTOVOLTAICO', 2, 1);
insert into ticket_equipofalla values ('EE-027', 'TABLERO DE CONTROL DE CONMUTACION FOTOVOLTAICO', 2, 1);
insert into ticket_equipofalla values ('EE-028', 'RECTIFICADOR', 2, 1);
insert into ticket_equipofalla values ('EE-029', 'BANCO DE BATERIAS - RECTIFICADOR', 2, 1);
insert into ticket_equipofalla values ('EE-030', 'TABLERO DE DISTRIBUCION PRINCIPAL DC', 2, 1);
insert into ticket_equipofalla values ('EE-031', 'TABLERO DE DISTRIBUCION SECUNDARIO DC (PDU)', 2, 1);
insert into ticket_equipofalla values ('EE-032', 'UPS', 2, 1);
insert into ticket_equipofalla values ('EE-033', 'BANCO DE BATERIAS - UPS', 2, 1);
insert into ticket_equipofalla values ('EE-034', 'TABLERO DE DISTRIBUCION PRINCIPAL DE ENERGIA UPS', 2, 1);
insert into ticket_equipofalla values ('EE-035', 'TABLERO DE DISTRIBUCION SECUNDARIO DE ENERGIA UPS', 2, 1);
insert into ticket_equipofalla values ('EE-036', 'AIRE ACONDICIONADO', 2, 1);
-- TIPOFALLA
insert into ticket_tipofalla values ('EF-070', 'FALLA EN LA RED DE SUMINISTRO COMERCIAL', 2, 1);
insert into ticket_tipofalla values ('EF-071', 'TRANSFORMADOR MONOFASICO CON FALLA', 2, 1);
insert into ticket_tipofalla values ('EF-072', 'TRANSFORMADOR BIFASICO CON FALLA', 2, 1);
insert into ticket_tipofalla values ('EF-073', 'TRANSFORMADOR TRIFASICO CON FALLA', 2, 1);
insert into ticket_tipofalla values ('EF-074', 'ALARMA DE CORTE DE ENERGIA', 2, 1);
insert into ticket_tipofalla values ('EF-075', 'BAJO NIVEL DE VOLTAJE AC', 2, 1);
insert into ticket_tipofalla values ('EF-076', 'CORTE DE ENERGIA PROGRAMADO', 2, 1);
insert into ticket_tipofalla values ('EF-077', 'FALLA DE ENERGIA EN NODO DE TRANSPORTE', 2, 1);
insert into ticket_tipofalla values ('EF-078', 'FUSIBLE DE MEDIA TENSION QUEMADO', 2, 1);
insert into ticket_tipofalla values ('EF-079', 'TERMOMAGNETICO DE PILASTRA ABIERTO', 2, 1);
insert into ticket_tipofalla values ('EF-080', 'TERMOMAGNETICO DE TRANSFORMADOR ABIERTO', 2, 1);
insert into ticket_tipofalla values ('EF-081', 'TERMOMAGNETICO DE TDP ABIERTO', 2, 1);
insert into ticket_tipofalla values ('EF-082', 'GRAMPA DE LINEA MT ABIERTO', 2, 1);
insert into ticket_tipofalla values ('EF-083', 'GRAMPA DE LINEA MT CON FALLA', 2, 1);
insert into ticket_tipofalla values ('EF-084', 'AISLADOR TIPO CAMPANA CON FALLA', 2, 1);
insert into ticket_tipofalla values ('EF-085', 'LINEA MT CORTADO', 2, 1);
insert into ticket_tipofalla values ('EF-086', 'LINEA MT SUELTO', 2, 1);
insert into ticket_tipofalla values ('EF-087', 'CABLE DE ACOMETIDA CON FALLA', 2, 1);
insert into ticket_tipofalla values ('EF-088', 'CABLE DE ACOMETIDA CORTADO', 2, 1);
insert into ticket_tipofalla values ('EF-089', 'POSTE MT DEGRADADO', 2, 1);
insert into ticket_tipofalla values ('EF-090', 'GGE MONOFASICO CON FALLA', 2, 1);
insert into ticket_tipofalla values ('EF-091', 'GGE TRIFASICO CON FALLA', 2, 1);
insert into ticket_tipofalla values ('EF-092', 'CONFIGURACION DE GGE ESTACIONARIO', 2, 1);
insert into ticket_tipofalla values ('EF-093', 'BATERIA DE ARRANQUE DE GGE DEGRADADO', 2, 1);
insert into ticket_tipofalla values ('EF-094', 'CARGADOR DE BATERIA DE GGE CON FALLA', 2, 1);
insert into ticket_tipofalla values ('EF-095', 'CORREA DE GGE CON FALLA', 2, 1);
insert into ticket_tipofalla values ('EF-096', 'MOTOR DE ARRANQUE DE GGE CON FALLA', 2, 1);
insert into ticket_tipofalla values ('EF-097', 'BOMBA INYECTORA DE GGE CON FALLA', 2, 1);
insert into ticket_tipofalla values ('EF-098', 'BAJO NIVEL DE COMBUSTIBLE DIESEL', 2, 1);
insert into ticket_tipofalla values ('EF-099', 'TERMOMAGNETICO DE ATS ABIERTO', 2, 1);
insert into ticket_tipofalla values ('EF-100', 'TARJETA ATS CON FALLA', 2, 1);
insert into ticket_tipofalla values ('EF-101', 'SISTEMA FOTOVOLTAICO - EXPOSICION SOLAR INSUFICIENTE', 2, 1);
insert into ticket_tipofalla values ('EF-102', 'TABLERO DE CONMUTACION FOTOVOLTAICO CON FALLA', 2, 1);
insert into ticket_tipofalla values ('EF-103', 'RECTIFICADOR HUAWEI CON FALLA', 2, 1);
insert into ticket_tipofalla values ('EF-104', 'RECTIFICADOR ZTE CON FALLA', 2, 1);
insert into ticket_tipofalla values ('EF-105', 'PSU HUAWEI CON FALLA', 2, 1);
insert into ticket_tipofalla values ('EF-106', 'PSU ZTE CON FALLA', 2, 1);
insert into ticket_tipofalla values ('EF-107', 'CONFIGURACION DE RECTIFICADOR', 2, 1);
insert into ticket_tipofalla values ('EF-108', 'BANCO DE BATERIAS DEGRADADO', 2, 1);
insert into ticket_tipofalla values ('EF-109', 'CELDA DE BATERIA DEGRADADA', 2, 1);
insert into ticket_tipofalla values ('EF-110', 'TERMOMAGNETICO DE TABLERO PRINCIPAL DC DESACTIVADO', 2, 1);
insert into ticket_tipofalla values ('EF-111', 'TERMAGNETICO DE TABLERO SECUNDARIO DC DESACTIVADO', 2, 1);
insert into ticket_tipofalla values ('EF-112', 'UPS CON FALLA', 2, 1);
insert into ticket_tipofalla values ('EF-113', 'BANCO DE BATERIAS UPS DEGRADADO', 2, 1);
insert into ticket_tipofalla values ('EF-114', 'TERMOMAGNETICO DE TABLERO PRINCIPAL UPS DESACTIVADO', 2, 1);
insert into ticket_tipofalla values ('EF-115', 'TERMAGNETICO DE TABLERO SECUNDARIO UPS DESACTIVADO', 2, 1);
insert into ticket_tipofalla values ('EF-116', 'A.A. INHIBIDO', 2, 1);
insert into ticket_tipofalla values ('EF-117', 'A.A. TIPO MOCHILA CON FALLA', 2, 1);
insert into ticket_tipofalla values ('EF-118', 'A.A. TIPO SPLIT CON FALLA', 2, 1);
insert into ticket_tipofalla values ('EF-119', 'MOTOR DE VENTILADOR CON FALLA', 2, 1);
insert into ticket_tipofalla values ('EF-120', 'TERMOMAGNETICO DE A.A. ABIERTO', 2, 1);
insert into ticket_tipofalla values ('EF-121', 'ARRANCADOR SUAVE DE A.A. CON FALLA', 2, 1);
insert into ticket_tipofalla values ('EF-122', 'CAPACITOR DE ARRANQUE DE COMPRESOR CON FALLA', 2, 1);
insert into ticket_tipofalla values ('EF-123', 'CAPACITOR DE ARRANQUE DE VENTILADOR CON FALLA', 2, 1);
insert into ticket_tipofalla values ('EF-124', 'BAJO NIVEL DE GAS REFRIGERANTE', 2, 1);
insert into ticket_tipofalla values ('EF-125', 'FUGA DE GAS REFRIGERANTE', 2, 1);
insert into ticket_tipofalla values ('EF-126', 'ESTRACTOR DE AIRE INHIBID0', 2, 1);
insert into ticket_tipofalla values ('EF-127', 'ESTRACTOR DE AIRE CON FALLA INTERNA', 2, 1);

-- SOLUCION
insert into ticket_solucion values ('ES-060', 'RESTABLECIMIENTO DE ENERGIA POR LA EMPRESA DISTRIBUIDORA', 2, 1);
insert into ticket_solucion values ('ES-061', 'CAMBIO DE TRANSFORMADOR MONOFASICO', 2, 1);
insert into ticket_solucion values ('ES-062', 'CAMBIO DE TRANSFORMADOR BIFASICO', 2, 1);
insert into ticket_solucion values ('ES-063', 'CAMBIO DE TRANSFORMADOR TRIFASICO', 2, 1);
insert into ticket_solucion values ('ES-064', 'SUMINISTRO DE ENERGIA CON GGE ESTACIONARIO', 2, 1);
insert into ticket_solucion values ('ES-065', 'SUMINISTRO DE ENERGIA CON GGE PORTATIL', 2, 1);
insert into ticket_solucion values ('ES-066', 'RESTABLECIMIENTO DE ENERGIA EN NODO DE TRANSPORTE', 2, 1);
insert into ticket_solucion values ('ES-067', 'CAMBIO DE FUSIBLE MT EN DERIVACION PRINCIPAL', 2, 1);
insert into ticket_solucion values ('ES-068', 'CAMBIO DE FUSIBLE MT EN PUESTO DE TRANSFORMACION', 2, 1);
insert into ticket_solucion values ('ES-069', 'CIERRE DE TERMOMAGNETICO EN PILASTRA', 2, 1);
insert into ticket_solucion values ('ES-070', 'CIERRE DE TERMOMAGNETICO EN PUESTO DE TRANSFORMADOR', 2, 1);
insert into ticket_solucion values ('ES-071', 'CIERRE DE TERMOMAGNETICO EN TDP', 2, 1);
insert into ticket_solucion values ('ES-072', 'CIERRE DE GRAMPA DE LINEA MT', 2, 1);
insert into ticket_solucion values ('ES-073', 'CAMBIO DE GRAMPA DE LINEA MT', 2, 1);
insert into ticket_solucion values ('ES-074', 'CAMBIO DE AISLADOR TIPO CAMPANA', 2, 1);
insert into ticket_solucion values ('ES-075', 'EMPALME DE LINEA MT', 2, 1);
insert into ticket_solucion values ('ES-076', 'ASEGURAMIENTO DE LINEA MT', 2, 1);
insert into ticket_solucion values ('ES-077', 'CAMBIO DE CABLE DE ACOMETIDA', 2, 1);
insert into ticket_solucion values ('ES-078', 'EMPALME DE CABLE DE ACOMETIDA', 2, 1);
insert into ticket_solucion values ('ES-079', 'CAMBIO DE POSTE MT', 2, 1);
insert into ticket_solucion values ('ES-080', 'CAMBIO DE GGE MONOFASICO', 2, 1);
insert into ticket_solucion values ('ES-081', 'CAMBIO DE GGE TRIFASICO', 2, 1);
insert into ticket_solucion values ('ES-082', 'CONFIGURACION DE GGE ESTACIONARIO', 2, 1);
insert into ticket_solucion values ('ES-083', 'INSTALACION DE BATERIA DE ARRANQUE', 2, 1);
insert into ticket_solucion values ('ES-084', 'CAMBIO DE BATERIA DE ARRANQUE', 2, 1);
insert into ticket_solucion values ('ES-085', 'INSTALACION DE CARGADOR DE BATERIA', 2, 1);
insert into ticket_solucion values ('ES-086', 'CAMBIO DE CARGADOR DE BATERIA', 2, 1);
insert into ticket_solucion values ('ES-087', 'CAMBIO DE MOTOR DE ARRANQUE DE GGE', 2, 1);
insert into ticket_solucion values ('ES-088', 'CAMBIO DE BOMBA INYECTORA DE GGE', 2, 1);
insert into ticket_solucion values ('ES-089', 'CAMBIO DE CORREA DE GGE', 2, 1);
insert into ticket_solucion values ('ES-090', 'CARGA DE COMBUSTIBLE DIESEL', 2, 1);
insert into ticket_solucion values ('ES-091', 'CIERRE DE TERMOMAGNETICO EN ATS', 2, 1);
insert into ticket_solucion values ('ES-092', 'CAMBIO DE TARJETA ATS', 2, 1);
insert into ticket_solucion values ('ES-093', 'DESINSTALACION DE TARJETA ATS', 2, 1);
insert into ticket_solucion values ('ES-094', 'RESET FISICO A TARJETA ATS', 2, 1);
insert into ticket_solucion values ('ES-095', 'EXPOSICION SOLAR A LOS PANELES SOLARES', 2, 1);
insert into ticket_solucion values ('ES-096', 'CAMBIO DE PANEL FOTOVOLTAICO', 2, 1);
insert into ticket_solucion values ('ES-097', 'CAMBIO DE TABLERO DE CONMUTACION FOTOVOLTAICO', 2, 1);
insert into ticket_solucion values ('ES-098', 'CAMBIO DE RECTIFICADOR HUAWEI', 2, 1);
insert into ticket_solucion values ('ES-099', 'CAMBIO DE RECTIFICADOR ZTE', 2, 1);
insert into ticket_solucion values ('ES-100', 'CAMBIO DE PSU HUAWEI', 2, 1);
insert into ticket_solucion values ('ES-101', 'CAMBIO DE PSU ZTE', 2, 1);
insert into ticket_solucion values ('ES-102', 'DESINSTALACION DE PSU HUAWEI', 2, 1);
insert into ticket_solucion values ('ES-103', 'DESINSTALACION DE PSU ZTE', 2, 1);
insert into ticket_solucion values ('ES-104', 'CONFIGURACION DE CARGA A BANCO DE BATERIAS', 2, 1);
insert into ticket_solucion values ('ES-105', 'CAMBIO DE BANCO DE BATERIAS', 2, 1);
insert into ticket_solucion values ('ES-106', 'CAMBIO DE CELDA', 2, 1);
insert into ticket_solucion values ('ES-107', 'INSTALACION DE BANCO DE BATERIAS', 2, 1);
insert into ticket_solucion values ('ES-108', 'CIERRE DE TERMOMAGNETICO DE TABLERO PRINCIPAL DC', 2, 1);
insert into ticket_solucion values ('ES-109', 'CIERRE DE TERMOMAGNETICO DE TABLERO SECUNDARIO DC', 2, 1);
insert into ticket_solucion values ('ES-110', 'CAMBIO DE UPS', 2, 1);
insert into ticket_solucion values ('ES-111', 'RESET FISICO UPS', 2, 1);
insert into ticket_solucion values ('ES-112', 'CAMBIO DE BANCO DE BATERIAS UPS', 2, 1);
insert into ticket_solucion values ('ES-113', 'CIERRE DE TERMOMAGNETICO DE TABLERO PRINCIPAL UPS', 2, 1);
insert into ticket_solucion values ('ES-114', 'CIERRE DE TERMOMAGNETICO DE TABLERO SECUNDARIO UPS', 2, 1);
insert into ticket_solucion values ('ES-115', 'RESET FISICO A.A.', 2, 1);
insert into ticket_solucion values ('ES-116', 'CAMBIO DE A.A. TIPO MOCHILA', 2, 1);
insert into ticket_solucion values ('ES-117', 'CAMBIO DE A.A. TIPO VENTANA', 2, 1);
insert into ticket_solucion values ('ES-118', 'CAMBIO DE COMPRESOR', 2, 1);
insert into ticket_solucion values ('ES-119', 'CAMBIO DE MOTOR DE VENTILADOR', 2, 1);
insert into ticket_solucion values ('ES-120', 'CIERRE DE TERMOMAGNETICO DE A.A.', 2, 1);
insert into ticket_solucion values ('ES-121', 'CAMBIO DE ARRANCADOR SUAVE DE A.A.', 2, 1);
insert into ticket_solucion values ('ES-122', 'CAMBIO DE CAPACITOR DE ARRANQUE DE COMPRESOR', 2, 1);
insert into ticket_solucion values ('ES-123', 'CAMBIO DE CAPACITOR DE ARRANQUE DE VENTILADOR', 2, 1);
insert into ticket_solucion values ('ES-124', 'CARGA DE GAS REFRIGERANTE', 2, 1);
insert into ticket_solucion values ('ES-125', 'AISLACION DE CAÑERIA DE A.A.', 2, 1);
insert into ticket_solucion values ('ES-126', 'RECONEXION DE CABLE DE ALIMENTACION DE ESTRACTOR DE AIRE', 2, 1);
insert into ticket_solucion values ('ES-127', '	REEMPLAZO DE ESTRACTOR DE AIRE', 2, 1);
