/* 22.10.2022 */
ALTER TABLE `rutina015` ADD COLUMN table_e1 LONGTEXT;
ALTER TABLE `rutina015` ADD COLUMN table_e2 LONGTEXT;

DELETE FROM rutina_titulos WHERE codform = '001';
insert into rutina_titulos (titulo, codform) values ('Fotografia N.1 - Panorámica de gabinete de baterías puerta cerrada.', '001');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.2 - Panorámica de gabinete de baterías puerta abierta.', '001');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.3 - Marca modelo y capacidad de las baterías.', '001');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.4 - Temperatura de las baterías.', '001');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.5 - Voltaje de descarga del banco.', '001');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.6 - Corriente total (Consumo de equipos).', '001');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.7 - Limpieza de los bancos de baterías.', '001');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.8 - Ajuste de bornes de banco de baterías.', '001');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.9 - Ajuste de bornes de banco de baterías.', '001');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.10 - Observaciones (antes - despues).', '001');

DELETE FROM rutina_titulos WHERE codform = '002';

insert into rutina_titulos (titulo, codform) values ('Fotografia N.1 - Gabinete de rectificadores puerta cerrada.', '002');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.2 - Gabinete de rectificadores puerta abierta, con equipos que energiza.', '002');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.3 - Vista frontal de rectificadores.', '002');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.4 - Marca modelo y capacidad de los rectificadores.', '002');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.5 - Corriente AC de entrada a los rectificadores.', '002');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.6 - Voltaje se salida DC.', '002');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.7 - Corriente de salida DC.', '002');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.8 - Limpieza de los rectificadores.', '002');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.9 - Limpieza slots de los rectificadores.', '002');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.10 - Observaciones (antes - despues).', '002');

DELETE FROM rutina_titulos WHERE codform = '007';
insert into rutina_titulos (titulo, codform) values ('Fotografia N.1 - Seccionador de linea punto de arranque. (No cuenta con pararrayos)', '007');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.2 - Estado postación extensión media tensión.', '007');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.3 - Pararrayos, seccionador punto de transformación.', '007');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.4 - Bajante sistema de puesta a tierra transformador.', '007');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.5 - Placa de referencia del transformador.', '007');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.6 - Medición de tensión  salida del transformador (V).', '007');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.7 - Medición de corriente de operación salida transformador (A).', '007');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.8 - Medida sistema completo puesta a tierra en punto de Transformador (pinza).', '007');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.9 - Medida sistema completo puesta a tierra en punto de Transformador (Telurometro).', '007');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.10 - Observaciones (antes - despues).', '007');

DELETE FROM rutina_titulos WHERE codform = '008';
insert into rutina_titulos (titulo, codform) values ('Fotografia N.1 - Estructura  general pilastra, cable dúplex de alimentación y bastón o torreta.', '008');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.2 - Rejilla de seguridad caja medidor y candado de seguridad.', '008');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.3 - Cajas en pilastra.', '008');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.4 - Cámara de energía', '008');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.5 - Medidor de energía, serie y consumo.', '008');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.6 - Protector transcientes de primer nivel y termico de habilitacion.', '008');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.7 - Ajuste de Bornes Protector transiente.', '008');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.8 - Ajuste de Bornes térmico de habilitación.', '008');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.9 - Barra colectora de SPT en pilastra.', '008');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.10 - Limpieza  de cajas medidor protección y sistema de tierra.', '008');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.11 - Ductos de ingreso/salida cajas pilastra.', '008');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.12 - Medición de tensión en operación  ingreso medidor (V).', '008');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.13 - Medición de corriente en operación medidor(A).', '008');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.14 - Medición de Voltaje Neutro-Tierra (V).', '008');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.15 - Distribución Energía AC TDP.', '008');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.16 - Protector transcientes de segundo nivel y termico de habilitacion TDP.', '008');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.17 - Datos tecnicos del TDP.', '008');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.18 - Medida puesta a tierra Pilastra (Pinza).', '008');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.19 - Medida puesta a tierra Pilastra (Telurometro).', '008');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.20 - Observaciones (antes - despues).', '008');

DELETE FROM rutina_titulos WHERE codform = '006';
insert into rutina_titulos (titulo, codform) values ('Fotografia N.1 - Arreglo de paneles.', '006');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.2 - Placa de refencia de cada panel.', '006');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.3 - Juntion Box.', '006');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.4 - Votaje total de paneles solares juntion box.', '006');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.5 - Corriente total de paneles solares juntion box.', '006');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.6 - Corriente en arreglo solar.', '006');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.7 - Vista gabinete con reguladores.', '006');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.8 - Placa de referencia reguladores de voltaje.', '006');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.9 - Voltaje de salida en Display.', '006');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.10 - Corriente de salida en display.', '006');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.11 - Limpieza de los paneles.', '006');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.12 - Limpieza de los reguladores y slot.', '006');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.13 - Observaciones (antes - despues).', '006');

DELETE FROM rutina_titulos WHERE codform = '009';
insert into rutina_titulos (titulo, codform) values ('Fotografia N.1 - Panoramica del ATS puerta cerrada.', '009');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.2 - Panoramica del ATS puerta abierta.', '009');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.3 - Valor del Voltímetro ATS.', '009');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.4 - Valor del Voltímetro ATS.', '009');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.5 - Valor del frecuencímetro ATS.', '009');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.6 - Conexiones sistemas puesto a tierra.', '009');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.7 - Fusibles de protección.', '009');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.8 - Relés control.', '009');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.9 - Ajuste de borneras circuito de transferencia, protección y alimentación.', '009');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.10 - Sellado  de Ductos y etiquetado de cables de energía.', '009');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.11 - Placa de referencia del ATS.', '009');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.12 - Observaciones (antes - despues).', '009');

DELETE FROM rutina_titulos WHERE codform = '011';
insert into rutina_titulos (titulo, codform) values ('Fotografia N.1 - Panoramica del grupo electrogeno.', '011');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.2 - Placa de referencia del grupo electrógeno.', '011');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.3 - Placa de referencia del generador.', '011');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.4 - Estado de fugas de combustible, bomba, lubricante refrigerante.', '011');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.5 - Estado físico de batería de arranque.', '011');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.6 - Estado conexiones eléctricas.', '011');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.7 - Estado físico de display.', '011');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.8 - Estado de limpieza del grupo.', '011');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.9 -  Estado del aceite (en la varilla)', '011');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.10 - Limpieza del filtro de aire.', '011');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.11 - Nivel de refrigerante en el radiador', '011');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.12 - Temperatura superficial del precalentador, % de combustiblle y tension del cargador de bateria (Antes de operar el GG.GG.).', '011');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.13 - Horometro en display de grupo.', '011');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.14 - Temperatura, presion, revoluciones, tension, corriente y frecuencia del grupo en operacion..', '011');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.15 - Tanque de combustble.', '011');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.16 - Limpieza del grupo.', '011');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.17 - Observaciones (antes - despues).', '011');

DELETE FROM rutina_titulos WHERE codform = '012';
insert into rutina_titulos (titulo, codform) values ('Fotografia N.1 - Protector de 1er nivel.', '012');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.2 - Ajuste de bornes en protector.', '012');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.3 - Protector de 2do nivel TDP.', '012');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.4 - Protector de 2do nivel ATS.', '012');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.5 - Bajante cable Franklin en Torre.', '012');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.6 - Pararrayos Franklin.', '012');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.7 - Soldadura Cadwel camaras de inspeccion estacion.', '012');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.8 - Verificacion cableado de tierra desde la barra colectora a equipos en general.', '012');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.9 - Camaras de inspeccion sistema a tierra.', '012');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.10 - Limpieza de Barras colectoras: Torre, Caseta de equipos.', '012');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.11 - Ajuste de conexiones en Barras colectoras: Torre, Caseta de equipos.', '012');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.12 - Ajuste de conexiones en Barras colectoras: Torre, Caseta de equipos.', '012');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.13 - Medida Potencial entre el sistema de tierra y Neutro Termico Pilastra.', '012');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.14 - Medida Potencial entre el neutro y masa Termico Pilastra.', '012');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.15 - Medida a tierra en bajante de pararrayos (pinza).', '012');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.16 - Medida a tierra en bajante de pararrayos (Telurometro).', '012');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.17 - Medida a tierra barra colectora  Pilastra (pinza).', '012');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.18 - Medida a tierra barra colectora  Pilastra (Telurometro).', '012');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.19 - Medida a tierra barra colectora bajante Torre (pinza).', '012');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.20 - Medida a tierra barra colectora bajante Torre (Telurometro).', '012');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.21 - Medida a tierra base torre (pinza).', '012');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.22 - Medida a tierra base torre (Telurometro).', '012');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.23 - Medida a tierra rriostra torre (pinza).', '012');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.24 - Medida a tierra rriostra torre (Telurometro).', '012');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.25 - Medida a tierra barra colectora caseta equipos (pinza).', '012');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.26 - Medida a tierra barra colectora caseta equipos (Telurometro).', '012');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.27 - Medida a tierra camara de inspeccion (pinza).', '012');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.28 - Medida a tierra camara de inspeccion (Telurometro).', '012');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.29 - Medida a tierra barra colectora tablero electrico(pinza).', '012');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.30 - Medida a tierra barra colectora tablero electrico (Telurometro).', '012');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.31 - Medida a tierra barra colectora grupo electrogeno (pinza).', '012');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.32 - Medida a tierra barra colectora grupo electrogeno (Telurometro).', '012');
insert into rutina_titulos (titulo, codform) values ('Fotografia N.33 - Observaciones (antes - despues).', '012');
